# -*- coding: utf-8 -*-
"""B6LU.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ovq6QPQaQtR-7AEQjY3Ybfy1P48Q0-7
"""

n=int(input("enter number upto which you want to sum"))
i=1
sum=0
while(i<=n):
     sum=sum+i
     i=i+1
print("Sum=",sum)

num=int(input("enter a number:"))
if num<=1:
  print(num,"is not a prime number")
else:
  for i in range(2,num):
    if(num%i)==0:
      print(num,"is not a prime number")
      break
  else:
    print(num,"is a prime number")